version: '3.7'

services:
  backend:
    image: students
    build:
      context: .
    env_file:
      - ./.env

  proxy:
    build:
      context: ./proxy
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - backend


